# Generated by Django 5.1.7 on 2026-03-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='total_requests_raised',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
