# Generated by Django 5.1.7 on 2026-03-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_donor_latitude_donor_longitude_alter_donor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='is_verified',
            new_name='is_aadhaar_verified',
        ),
    ]
