# Generated by Django 5.1.7 on 2026-06-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_is_verified_donor_is_aadhaar_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('donor', 'Donor'), ('partner', 'Partner')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('success', 'Success'), ('no_account', 'Account not found'), ('invalid_password', 'Wrong password'), ('locked', 'Account locked'), ('not_verified', 'Partner not verified/live')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['identifier', 'created_at'], name='users_login_identif_a8815a_idx'), models.Index(fields=['ip_address', 'created_at'], name='users_login_ip_addr_4650d9_idx')],
            },
        ),
    ]
