# Generated by Django 5.1.7 on 2026-06-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='reason',
            field=models.CharField(choices=[('success', 'Success'), ('no_account', 'Account not found'), ('invalid_password', 'Wrong password'), ('locked', 'Account locked'), ('not_verified', 'Partner not verified/live'), ('rate_limited', 'Rate limited')], max_length=30),
        ),
    ]
