# Generated by Django 5.1.7 on 2026-03-21 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('users', '0002_donor_total_requests_raised'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('units_donated', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='completed', max_length=15)),
                ('score_change', models.FloatField(default=0.0)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('is_verified_by_bank', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_history', to='users.donor')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to='partners.partners')),
            ],
        ),
    ]
