# Generated by Django 5.1.7 on 2026-03-21 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_records', to='requests_app.partnerdonorrequest'),
        ),
    ]
