# Generated by Django 5.1.7 on 2026-03-21 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('users', '0002_donor_total_requests_raised'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('call', 'Call')], max_length=20)),
                ('trigger', models.CharField(choices=[('donor_request', 'Donor Request'), ('request_expiry', 'Request Expiry'), ('request_fulfilled', 'Request Fulfilled'), ('donor_accepted', 'Donor Accepted'), ('bank_verified', 'Bank Verified'), ('score_updated', 'Score Updated'), ('account_locked', 'Account Locked')], max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('is_fallback', models.BooleanField(default=False)),
                ('fallback_attempted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.donor')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='partners.partners')),
            ],
        ),
    ]
