# Generated by Django 5.1.7 on 2026-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='trigger',
            field=models.CharField(choices=[('donor_request', 'Donor Request'), ('request_expiry', 'Request Expiry'), ('request_fulfilled', 'Request Fulfilled'), ('donor_accepted', 'Donor Accepted'), ('bank_verified', 'Bank Verified'), ('score_updated', 'Score Updated'), ('account_locked', 'Account Locked'), ('password_reset', 'Password Reset')], max_length=50),
        ),
    ]
