# Generated by Django 5.1.7 on 2026-03-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('partner_type', models.CharField(choices=[('government', 'Government'), ('private multi-specialty', 'Private Multi-Specialty'), ('blood-bank', 'BLOOD BANK')], max_length=50)),
                ('license_id', models.CharField(max_length=50, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('convenience_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fees_description', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
