# Generated by Django 5.1.7 on 2026-03-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partners_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
