# Generated by Django 5.1.7 on 2026-03-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partners_city_partners_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='convenience_fees',
            new_name='convenience_fee',
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='fees_description',
            new_name='facility',
        ),
        migrations.AddField(
            model_name='partners',
            name='fee_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partners',
            name='partner_type',
            field=models.CharField(choices=[('government', 'Government'), ('private_multi_specialty', 'Private Multi-Specialty'), ('blood_bank', 'Blood Bank')], max_length=50),
        ),
    ]
