# Generated by Django 5.1.7 on 2026-03-21 11:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('users', '0002_donor_total_requests_raised'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attender_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
                ('quantity', models.PositiveIntegerField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('hospital_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('attender_name', models.CharField(max_length=100)),
                ('attender_phone', models.CharField(max_length=15)),
                ('id_type', models.CharField(max_length=50)),
                ('id_no', models.CharField(max_length=50)),
                ('doctor_letter_head', models.CharField(max_length=100)),
                ('attnder_id_proof', models.ImageField(blank=True, null=True, upload_to='attender_id_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('attender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.donor')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerDonorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('cancellation_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.donor')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partners')),
            ],
        ),
    ]
