# Generated by Django 5.1.7 on 2026-03-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
        ('users', '0003_donor_latitude_donor_longitude_alter_donor_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attender_request',
            new_name='AttenderRequest',
        ),
    ]
