# Generated by Django 5.1.7 on 2026-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_rename_attender_request_attenderrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attenderrequest',
            name='attnder_id_proof',
        ),
        migrations.RemoveField(
            model_name='attenderrequest',
            name='doctor_letter_head',
        ),
        migrations.AddField(
            model_name='attenderrequest',
            name='attender_id_proof',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='attenderrequest',
            name='doctor_letterhead',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attenderrequest',
            name='patient_photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
