# Generated by Django 5.1.7 on 2026-03-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_remove_attenderrequest_attnder_id_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attenderrequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attenderrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
