# Generated by Django 5.1.7 on 2026-03-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_attenderrequest_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerdonorrequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
