# Generated by Django 5.1.7 on 2026-03-31 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_rename_convenience_fees_partners_convenience_fee_and_more'),
        ('requests_app', '0006_otpcode'),
        ('users', '0004_rename_is_verified_donor_is_aadhaar_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttenderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('has_complaint', models.BooleanField(default=False)),
                ('complaint_type', models.CharField(blank=True, choices=[('exchange_condition', 'Asked for blood exchange'), ('overcharging', 'Charged extra fees'), ('misbehavior', 'Staff misbehavior'), ('fake_stock', 'Showed wrong stock availability'), ('other', 'Other')], max_length=50, null=True)),
                ('complaint_detail', models.TextField(blank=True, null=True)),
                ('complaint_status', models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='users.donor')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='partners.partners')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='requests_app.attenderrequest')),
            ],
        ),
        migrations.CreateModel(
            name='InterPartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('convenience_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attender_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_partner_requests', to='requests_app.attenderrequest')),
                ('fulfilling_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_requests_received', to='partners.partners')),
                ('requesting_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_requests_sent', to='partners.partners')),
            ],
        ),
    ]
