# Generated by Django 5.1.7 on 2026-04-03 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_donationcamp_campenrollment'),
        ('requests_app', '0007_attenderrating_interpartnerrequest'),
        ('users', '0004_rename_is_verified_donor_is_aadhaar_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attenderrating',
            name='complaint_type',
            field=models.CharField(blank=True, choices=[('exchange_condition', 'Asked for blood exchange'), ('overcharging', 'Charged extra fees'), ('misbehavior', 'Staff misbehavior'), ('fake_stock', 'Wrong stock shown'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DonorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='users.donor')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_ratings_given', to='partners.partners')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_rating', to='requests_app.partnerdonorrequest')),
            ],
        ),
    ]
