# Generated by Django 5.1.7 on 2026-04-03 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_donationcamp_campenrollment'),
        ('requests_app', '0008_alter_attenderrating_complaint_type_donorrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attenderrating',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='partners.partners'),
        ),
    ]
