# Generated by Django 5.1.7 on 2026-04-24 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_donationcamp_campenrollment'),
        ('requests_app', '0009_alter_attenderrating_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='attenderrequest',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_attender_requests', to='partners.partners'),
        ),
    ]
