# Generated by Django 5.1.7 on 2026-05-13 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_donationcamp_campenrollment'),
        ('requests_app', '0010_attenderrequest_fulfilled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='attenderrating',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='partners.partners'),
        ),
    ]
