# Generated by Django 5.1.7 on 2026-03-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('donor', 'Donor'), ('partner', 'Partner')], max_length=10)),
                ('message', models.CharField(choices=[('on_the_way', 'On my way'), ('reached', 'Reached the bank'), ('unable_to_come', 'Unable to come'), ('delayed', 'Running late'), ('donated', 'Donation completed')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
