# Generated by Django 5.1.7 on 2026-03-21 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='requests_app.partnerdonorrequest'),
        ),
    ]
