# Generated by Django 5.1.7 on 2026-03-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(choices=[('on_the_way', 'On my way'), ('reached', 'Reached the bank'), ('unable_to_come', 'Unable to come'), ('delayed', 'Running late'), ('donated', 'Donation completed'), ('otp_generated', 'OTP Generated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender_type',
            field=models.CharField(choices=[('donor', 'Donor'), ('partner', 'Partner'), ('system', 'System')], max_length=10),
        ),
    ]
