# Generated by Django 5.1.7 on 2026-06-18 15:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_type', models.CharField(max_length=10)),
                ('user_id', models.IntegerField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('replaced_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['token_id'], name='auth_token__token_i_d398e7_idx')],
            },
        ),
    ]
